name: black-checker

on: [pull_request, push]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Black Code Formatter
        uses: psf/black@stable
        with:
          version: "25.9.0"
          options: "--check --diff"
